In [1]:
import numpy as np
from numpy import genfromtxt

data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [2]:
data


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
data.shape

(1372, 5)

In [8]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [13]:
x = features
y = labels
x,y

(array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
        [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
        [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
        ...,
        [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
        [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
        [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]]),
 array([0., 0., 0., ..., 1., 1., 1.]))

In [16]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.33,random_state = 42)
#x_train,x_test,y_train,y_test

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()
scaler_object.fit(x_train)
scaled_x_train = scaler_object.transform(x_train)
scaled_x_test = scaler_object.transform(x_test)

In [22]:
x_train.max()
scaled_x_train.max()

# X_train
# scaled_X_train

1.0000000000000002

In [24]:
from keras.models import Sequential
from keras.layers import Dense

# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [28]:
# Play around with number of epochs as well!
model.fit(scaled_x_train,y_train,epochs=100, verbose=2)

Epoch 1/100
 - 0s - loss: 0.0248 - acc: 0.9956
Epoch 2/100
 - 0s - loss: 0.0245 - acc: 0.9935
Epoch 3/100
 - 0s - loss: 0.0236 - acc: 0.9967
Epoch 4/100
 - 0s - loss: 0.0230 - acc: 0.9978
Epoch 5/100
 - 0s - loss: 0.0227 - acc: 0.9967
Epoch 6/100
 - 0s - loss: 0.0223 - acc: 0.9978
Epoch 7/100
 - 0s - loss: 0.0219 - acc: 0.9978
Epoch 8/100
 - 0s - loss: 0.0220 - acc: 0.9956
Epoch 9/100
 - 0s - loss: 0.0219 - acc: 0.9978
Epoch 10/100
 - 0s - loss: 0.0219 - acc: 0.9978
Epoch 11/100
 - 0s - loss: 0.0212 - acc: 0.9978
Epoch 12/100
 - 0s - loss: 0.0210 - acc: 0.9978
Epoch 13/100
 - 0s - loss: 0.0213 - acc: 0.9946
Epoch 14/100
 - 0s - loss: 0.0210 - acc: 0.9978
Epoch 15/100
 - 0s - loss: 0.0204 - acc: 0.9956
Epoch 16/100
 - 0s - loss: 0.0203 - acc: 0.9978
Epoch 17/100
 - 0s - loss: 0.0200 - acc: 0.9978
Epoch 18/100
 - 0s - loss: 0.0203 - acc: 0.9956
Epoch 19/100
 - 0s - loss: 0.0198 - acc: 0.9978
Epoch 20/100
 - 0s - loss: 0.0197 - acc: 0.9978
Epoch 21/100
 - 0s - loss: 0.0193 - acc: 0.9978
E

In [34]:
model.predict_classes(scaled_x_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [35]:
model.metrics_names

['loss', 'acc']

In [37]:
model.evaluate(x=scaled_x_test,y=y_test)

453/453 [==============================] - 0s 19us/step


[0.018602733181380393, 0.9955849889624724]

In [38]:
from sklearn.metrics import confusion_matrix,classification_report

In [40]:
predictions = model.predict_classes(scaled_x_test)

In [42]:
confusion_matrix(y_test,predictions)

array([[257,   0],
       [  2, 194]], dtype=int64)

In [44]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.99      1.00      1.00       257
        1.0       1.00      0.99      0.99       196

avg / total       1.00      1.00      1.00       453



In [46]:
model.save('myfirstmodel.h5')

In [49]:
from keras.models import load_model

In [50]:
newmodel = load_model('myfirstmodel.h5')

In [51]:
newmodel.predict_classes(x_test)

array([[0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    